### ISSUE TITLE
keda-operator running pod is not the leader when there's a keda-operator evicted pod

### ISSUE THREAD

**Issue by hila3000** [kedacore/keda#1030]
Hi,

I don't know if it's a bug or a feature request, so let me know if it is a feature request and I'll re-open it as such.

## Expected Behavior
keda-operator on running state should always get elected as the leader.
From search online, it says that the election is defined in the code that initializes the Manager object, a.k.a the keda-operator, so I assume it's a change needed to be on your side rather than any config changes in the yaml that deploys keda-operator.

## Actual Behavior
There was a keda-operator pod in evicted status, and the running keda-operator pod has this error-
`{"level":"info","ts":1597714708.2032764,"logger":"leader","msg":"Found existing lock","LockOwner":"keda-operator-6f74797b8b-jgz4c"}
{"level":"info","ts":1597714708.211356,"logger":"leader","msg":"Not the leader. Waiting."}`

Making the keda not work (a.k.a changes on scaledobjects not being reflected in the cluster).
Only when I deleted the evicted pod, the running keda-operator started working as expected (Gained leadership).

## Steps to Reproduce the Problem
get to a point you have in the cluster 2 keda-operator pods - one in evicted status, one in running status.

## Specifications
  - **KEDA Version**: 1.5.0
  - **Platform & Version:** GCP GKE Cluster, not sure what you mean by platform version.
  - **Kubernetes Version:** 1.14.10-gke.42
  - **Scaler(s):** keda-scaledobject

**Comment by zroubalik** [comment]
Hi, for the upcoming v2, we have added readiness/liveness probes for the Operator and the underlying library changed the way, how the leader is elected: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#leader-election

I think this should solve the issue.

**Comment by hila3000** [comment]
Thanks! Is there an estimation as to when v2 will get released?

**Comment by hila3000** [comment]
@zroubalik v2 is out :) Can you confirm this is working there as expected, and the issue I described here won't reproduce?

**Comment by zroubalik** [comment]
It should be working as expected.

**Comment by hila3000** [comment]
I'll try to test it soon and see. Thanks

**Comment by mohsinonxrm** [comment]
looks like this is still happening:
![image](https://user-images.githubusercontent.com/21046804/107842184-25a3ea80-6d76-11eb-8f6d-9a2938275fd8.png)

![image](https://user-images.githubusercontent.com/21046804/107842191-35bbca00-6d76-11eb-8299-147402271f81.png)

leader election lost...
