### ISSUE TITLE
metrics server: random errors periodically

### ISSUE THREAD

**Issue by surki** [kedacore/keda#1498]
I am seeing random errors periodically like below, which triggers our alerts, so was wondering if this is something known issue.

```
E0111 13:44:44.731177       1 writers.go:118] apiserver was unable to write a fallback JSON response: http2: stream closed
E0111 13:44:44.721911	    1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E0111 13:44:44.726531	    1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
```

## Expected Behavior

Do not see any errors under normal circumstances

## Logs from KEDA operator

*Provide logs from KEDA operator, if need be.*

```
E0111 13:44:44.731177       1 writers.go:118] apiserver was unable to write a fallback JSON response: http2: stream closed
E0111 13:44:44.721911	    1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E0111 13:44:44.726531	    1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}

```

## Specifications

  - **KEDA Version:** *2.0*
  - **Platform & Version:** *Linux*
  - **Kubernetes Version:** *1.18*
  - **Scaler(s):** *prometheus scaler*

**Comment by zroubalik** [comment]
This might be relevant, we are using the same metrics-adapter library as that project:
https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292#issuecomment-741773310

Seems like it should be solved in upcoming k8s releases, once we do the update.

**Comment by surki** [comment]
Okay, will wait for the update and get back later on this.

**Comment by surki** [comment]
FYI: just upgraded to new version (2.1.0), doesn't help, still seeing these errors in the logs.

**Comment by zroubalik** [comment]
@surki thanks for the info :( Based on this comment https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292#issuecomment-767444375, the issue might be solved by the latest custom-metrics-apiserver update.
Any chance that you can try to build KEDA with this dependency and give it a try? (I am not able to reproduce the issue).

**Comment by surki** [comment]
@zroubalik I already updated custom-metrics-apiserver to latest version available (did it as part of adding openapi spec changes). See [here](https://github.com/kedacore/keda/blob/main/go.mod#L29) 

Yes, the error doesn't seem to be critical (and our alerts already ignore that specific error). We could close this issue (unless someone wants to keep it open for following up later).

**Comment by zroubalik** [comment]
@surki you are right, I thought there's a newer version released in January, but sorry my mistake :)

I think we can keep this issue opened and close once it is resolved.
