### ISSUE TITLE
Deleting the ScaledObject before Deployment results in a crash

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#175]
### Steps to repro

Was following the steps for the rabbitMQ and Go sample.  If I delete the deployment before the scaled object I noticed from the logs the keda pod crashed and restarted.  It also left my HPA hanging around and I had to delete it manually even after removing the `ScaledObject`

### Expected behavior

Potentially just catch and throw a safe exception.  I wonder if it makes sense for the ScaledObject to be removed by KEDA automatically?

### Details

This was the logs in the previous container

> time="2019-05-10T06:13:20Z" level=info msg="Updated HPA with namespace default and name keda-hpa-rabbitmq-consumer"
time="2019-05-10T06:13:20Z" level=error msg="Error getting deployment: deployments.apps \"rabbitmq-consumer\" not found"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x1192bcc]

> goroutine 117 [running]:
github.com/kedacore/keda/pkg/handler.(*ScaleHandler).scaleDeployment(0xc000169bc0, 0x0, 0xc0000ba9a0, 0x0)
        /go/src/github.com/kedacore/keda/pkg/handler/scale_handler.go:240 +0x2c
github.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScale(0xc000169bc0, 0x1e7f760, 0xc000545c40, 0xc0000ba9a0)
        /go/src/github.com/kedacore/keda/pkg/handler/scale_handler.go:234 +0x1a4
github.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScaleLoop(0xc000169bc0, 0x1e7f760, 0xc000545c40, 0xc0000ba9a0, 0xc000434e01)
        /go/src/github.com/kedacore/keda/pkg/handler/scale_handler.go:186 +0x6a
created by github.com/kedacore/keda/pkg/handler.(*ScaleHandler).WatchScaledObjectWithContext
        /go/src/github.com/kedacore/keda/pkg/handler/scale_handler.go:53 +0x96

**Comment by yaron2** [comment]
I fixed this bug with PR https://github.com/kedacore/keda/pull/149.

It hasn't been pushed to the docker image. (verified it with the stack trace you put here).

**Comment by yaron2** [comment]
@ahmelsayed can you push master to latest?

**Comment by yaron2** [comment]
duplicated of https://github.com/kedacore/keda/issues/148

**Comment by ahmelsayed** [comment]
Done.

**Comment by APuertaSales** [comment]
I have the same problem. Installed Keda 1.3.0 but I still cannot delete the scaledobjects.
As I was trying to delete the complete namespace where the scaledobjects were deployed, I cannot create again the deployments to delete first the scaledobjects and then the deployments because the namespace is being terminated...
Any option?

**Comment by zroubalik** [comment]
@APuertaSales Was KEDA running when you deleted those ScaledObjects? There might be finalizers waiting there to be finalized by KEDA operator. I am not sure what else could be the problem.

**Comment by APuertaSales** [comment]
Thanks @zroubalik 
Keda was working, yes. Anyway I deleted the finalizers and the scaledobjected was deleted:
  - finalizer.keda.k8s.io

**Comment by pierreyves-lebrun** [comment]
I got the same issue with the latest version of Keda

**Comment by ianadavies** [comment]
@APuertaSales How do you delete the finalisers ?

**Comment by pierreyves-lebrun** [comment]
> @APuertaSales How do you delete the finalisers ?

You should be able to edit the `scaledobject` and delete the two lines specifying the finalizer
