### ISSUE TITLE
 KEDA authenticating with Azure returned 401 response

### ISSUE THREAD

**Issue by galiacheng** [kedacore/keda#5203]
### Report

I followed [Integrate KEDA with your Azure Kubernetes Service cluster](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda) to create scalers. But got error like the following ouput:

```
2023-11-24T07:56:16Z    ERROR   scale_handler   error getting metric for scaler {"scaledObject.Namespace": "sample-domain1-ns", "scaledObject.Name": "azure-managed-prometheus-scaler", "scaler": "prometheusScaler", "error": "prometheus query api returned error. status: 401 response: {\"status\":\"error\",\"errorType\":\"Unauthorized\",\"error\":\"Request does not contain an Authorization Header. RequestId: cdf5aeed646f4bd3bac28d27f740af2b\"}"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
        /workspace/pkg/scaling/scale_handler.go:522
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
        /workspace/pkg/metricsservice/server.go:47
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
        /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
        /workspace/vendor/google.golang.org/grpc/server.go:1376
google.golang.org/grpc.(*Server).handleStream
        /workspace/vendor/google.golang.org/grpc/server.go:1753
google.golang.org/grpc.(*Server).serveStreams.func1.1
        /workspace/vendor/google.golang.org/grpc/server.go:998
```

The KEDA operator is running:

```shell
$ kubectl get pod -n keda
NAME                                             READY   STATUS    RESTARTS   AGE
keda-admission-webhooks-7fcc448785-mhb5v         1/1     Running   0          44m
keda-operator-7f4cd6667f-dlnwd                   1/1     Running   0          44m
keda-operator-metrics-apiserver-c8649d49-w86zw   1/1     Running   0          44m
```

YAML file to create scaler:

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-managed-prometheus-trigger-auth
  namespace: sample-domain1-ns
spec:
  podIdentity:
      provider: azure-workload
      identityId: 6b882164-64ee-43dc-93bd-xxxxxxxxxxx
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-managed-prometheus-scaler
  namespace: sample-domain1-ns
spec:
  scaleTargetRef:
    apiVersion: weblogic.oracle/v1
    kind: Cluster
    name: sample-domain1-cluster-1
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: https://wls-prometheus-m2nz.eastus.prometheus.monitor.azure.com
      metricName: webapp_config_open_sessions_high_count
      query: sum(webapp_config_open_sessions_high_count{app="testwebapp"}[1m]) # Note: query must return a vector/scalar single element response
      threshold: '2'
      activationThreshold: '1'
    authenticationRef:
      name: azure-managed-prometheus-trigger-auth
```

### Expected Behavior

The scaler should work correctly.

### Actual Behavior

401 error: "Request does not contain an Authorization Header".

### Steps to Reproduce the Problem

See https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.0

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

Prometheus

**Comment by JorTurFer** [comment]
Hello, 
Could you double-check that KEDA has workload identity environment variables?
![image](https://github.com/kedacore/keda/assets/36899226/6b4ba556-c09d-4d4e-93ec-a9b23bd152e8)

**Comment by JorTurFer** [comment]
I've checked the docs you sent and the step where workload identity webhooks is installed is missing. Do you have workload identity webhook available in your cluster? It is the responsible for mutating KEDA pods with the envs above.
If you don't have it installed, you have to install it too

**Comment by JorTurFer** [comment]
@tomkerkhove , do you know how we can provide feedback to the docs. Having workload identity webhook ready and working in the cluster is a prerequisite too

**Comment by tomkerkhove** [comment]
@JorTurFer Nope, I think we can just file a bug on the repo with some details

**Comment by JorTurFer** [comment]
> @JorTurFer Nope, I think we can just file a bug on the repo with some details

done: https://github.com/MicrosoftDocs/azure-docs/issues/117442

**Comment by galiacheng** [comment]
Hello @JorTurFer thanks for your response. You are right, the root cause is workload identity is not enabled.

I think the doc has step to enable workload identity, but it provides a wrong command, please see:
![image](https://github.com/kedacore/keda/assets/59823457/51930733-9688-46b3-b731-9c352c4a6556)

The command should be:

```shell
az aks update -g $RESOURCE_GROUP -n $AKS_CLUSTER_NAME --enable-workload-identity
```

**Comment by galiacheng** [comment]
Unfortunately, even the workload identity enabled, 401 error still happened.

Now, KEDA has workload identity environment variables:
![image](https://github.com/kedacore/keda/assets/59823457/b9a262d3-cf7c-4593-85b0-30d476a19a92)

Attached the logs:

```text
2023-11-29T05:51:57Z    INFO    Adding Finalizer for the TriggerAuthentication  {"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication", "TriggerAuthentication": {"name":"azure-managed-prometheus-trigger-auth","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-trigger-auth", "reconcileID": "0313a52f-9d2a-4563-828c-0f4147588420"}
2023-11-29T05:51:58Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "83ce1036-d8c3-40e2-96c6-5e88c488828c"}
2023-11-29T05:51:58Z    INFO    Adding Finalizer for the ScaledObject   {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "83ce1036-d8c3-40e2-96c6-5e88c488828c"}
2023-11-29T05:51:58Z    INFO    Detected resource targeted for scaling  {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "83ce1036-d8c3-40e2-96c6-5e88c488828c", "resource": "weblogic.oracle/v1.Cluster", "name": "sample-domain1-cluster-1"}
2023-11-29T05:51:58Z    INFO    Creating a new HPA      {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "83ce1036-d8c3-40e2-96c6-5e88c488828c", "HPA.Namespace": "sample-domain1-ns", "HPA.Name": "keda-hpa-azure-managed-prometheus-scaler"}
2023-11-29T05:51:58Z    INFO    Initializing Scaling logic according to ScaledObject Specification      {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "83ce1036-d8c3-40e2-96c6-5e88c488828c"}
2023-11-29T05:51:58Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-managed-prometheus-scaler","namespace":"sample-domain1-ns"}, "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "reconcileID": "0c342ed9-2839-4e65-9aaf-75d5c46a0935"}
2023-11-29T05:51:58Z    ERROR   prometheus_scaler       prometheus query api returned error     {"type": "ScaledObject", "namespace": "sample-domain1-ns", "name": "azure-managed-prometheus-scaler", "error": "prometheus query api returned error. status: 401 response: {\"status\":\"error\",\"errorType\":\"Unauthorized\",\"error\":\"Request does not contain an Authorization Header. RequestId: 709efac180f44e71b9e83b5ffc44cfef\"}"}
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).ExecutePromQuery
        /workspace/pkg/scalers/prometheus_scaler.go:302
github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
        /workspace/pkg/scalers/prometheus_scaler.go:357
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:129
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
        /workspace/pkg/scaling/scale_handler.go:699
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
        /workspace/pkg/scaling/scale_handler.go:590
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:241
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:180
```

**Comment by JorTurFer** [comment]
> Hello @JorTurFer thanks for your response. You are right, the root cause is workload identity is not enabled.
> 
> I think the doc has step to enable workload identity, but it provides a wrong command, please see: ![image](https://private-user-images.githubusercontent.com/59823457/286487216-51930733-9688-46b3-b731-9c352c4a6556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDU2NDMsIm5iZiI6MTcwMTI0NTM0MywicGF0aCI6Ii81OTgyMzQ1Ny8yODY0ODcyMTYtNTE5MzA3MzMtOTY4OC00NmIzLWI3MzEtOWMzNTJjNGE2NTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODUzOGMwYTVjNTg3NjZkNGM5N2Q2NmQ5MTQyODkwZTA4YTgxYTNhOTBmODY5OGUxYjFjYTlkMmRiOTI4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UBzreTBFt3Ajxbttgk43YePrV5Jmm4XHQ4hewB-_RO8)
> 
> The command should be:
> 
> ```shell
> az aks update -g $RESOURCE_GROUP -n $AKS_CLUSTER_NAME --enable-workload-identity --enable-oidc-issuer
> ```
> 
> I've create an internal PR to fix the command in [MicrosoftDocs/azure-docs-pr/pull/259747](https://github.com/MicrosoftDocs/azure-docs-pr/pull/259747).

f**k, I didn't see that section when [I opened the issue and the PR adding the requirement of having workload identity installed](https://github.com/MicrosoftDocs/azure-docs/issues/117442). Could you remove the requirement too as part of your PR, considering that it's installed as part of the docs 🙏

**Comment by JorTurFer** [comment]
> Unfortunately, even the workload identity enabled, 401 error still happened.
>
> Now, KEDA has workload identity environment variables:

Restart KEDA operator. As the workload identity webhooks is a mutating webhook, you need to restart KEDA because nothing has changed in KEDA side and the pod is up & running, soi the mutating webhook can't do anything. Just restarting KEDA operator pod, WI webhook should mutate it and your workload should work

**Comment by galiacheng** [comment]
> Could you remove the requirement too as part of your PR, considering that it's installed as part of the docs 🙏

Sure, I will take care of it, thank you @JorTurFer

**Comment by JorTurFer** [comment]
I close this issue as solved, let us know if there is any other thing related
