### ISSUE TITLE
Release: 2.17.1

### ISSUE THREAD

**Issue by wozniakjan** [kedacore/keda#6724]
This issue template is used to track the rollout of a patch KEDA release due to two regressions introduced in [2.17.0](https://github.com/kedacore/keda/issues/6502).

For the full release process, we recommend reading [this document](https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md).

## Required items

- [x] https://github.com/kedacore/keda/issues/6696
- [x] https://github.com/kedacore/keda/issues/6712
- [x] https://github.com/kedacore/keda/issues/6703
- [x] https://github.com/kedacore/keda/issues/6730
- [x] https://github.com/kedacore/keda/issues/6725
- [x] https://github.com/kedacore/keda/pull/6737
- [x] https://github.com/kedacore/keda/pull/6772

## Queued up for the next patch release:
- [ ] https://github.com/kedacore/keda/pull/6781
- [ ] https://github.com/kedacore/keda/pull/6756

# Timeline

We aim to release this release in the week of May 12th - May 18th 2025.

## Progress

- [x] [Welcome message supported versions](https://github.com/kedacore/keda/blob/main/pkg/util/welcome.go#L29-L30) are up-to-date
- [x] Add the new version to [GitHub Bug report](https://github.com/kedacore/keda/blob/main/.github/ISSUE_TEMPLATE/3_bug_report.yml) template
- [x] Cherry-pick bugfixes from `main` branch
- [x] Create KEDA release
- [x] Setup continuous container scanning with Snyk
- [x] Prepare & ship Helm chart
- [x] Prepare next release
- [ ] Provide update in Slack
- [ ] Tweet about new release

**Comment by rickbrouwer** [comment]
In 2.17 a new Temporal scaler was also introduced. An issue was reported on this ([link](https://github.com/kedacore/keda/issues/6703)) with a possible fix ([link](https://github.com/kedacore/keda/pull/6707)). Is this also one to include in 2.17.1, or is it better to select it for a new release?

**Comment by wozniakjan** [comment]
I missed that, thank you! For sure, best to add to 2.17.1

**Comment by ebeltramo96** [comment]
what's the ETA for this release?

**Comment by VietND96** [comment]
I also would like to include this PR for Selenium Grid scaler #6772.

**Comment by joaopaulosr95** [comment]
Really looking forward to this so I can go live with my production workloads. Thanks for the heads up regarding #6707, @rickbrouwer.

**Comment by cschindlbeck** [comment]
All required items have been merged, can this be released now? @rickbrouwer / @wozniakjan 
We are running against two bugs that would be fixed by this

**Comment by joaopaulosr95** [comment]
I deployed v2.17.1 after #6777 release earlier today (thanks @wozniakjan), but I'm still getting connection reset by peer errors. By reviewing the changes implemented in #6703, I noticed the client forces TLS minimum version to be v1.3. Could it be that Temporal Server implements TLS v1.2, thus the connection cannot be made since the scaler doesn't accept the lower version?

**Comment by joaopaulosr95** [comment]
Just a heads up. I deployed v2.17.1 earlier today and I'm still seeing connection reset by peer errors while connecting my KEDA trigger to Temporal Cloud. Not sure if it applies, but perhaps there's a TLS version mismatch since the scaler forces the minVersion to be 1.3?

**Comment by cschindlbeck** [comment]
I deployed 2.17.1 and it indeed fixed https://github.com/kedacore/keda/issues/6712 and https://github.com/kedacore/keda/issues/6696 so thanks guys!

**Comment by cheelim1** [comment]
I'm still seeing connection reset by peer errors while connecting my KEDA trigger to Temporal Cloud in version `2.17.1`

**Comment by rickbrouwer** [comment]
> I'm still seeing connection reset by peer errors while connecting my KEDA trigger to Temporal Cloud in version `2.17.1`

This will be fixed in the next version: https://github.com/kedacore/keda/pull/6781

**Comment by SpiritZhou** [comment]
Click "close" button by accident
