### ISSUE TITLE
Keda 2.17.2 Temporal ScaledObject facing error reading server preface: remote error: tls: certificate required

### ISSUE THREAD

**Issue by cheelim1** [kedacore/keda#6865]
**keda version:**
v2.17.2

**Issue:** 
Using the keda scaled object for temporal https://keda.sh/docs/2.17/scalers/temporal/ facing the error
`"error": "failed to create Temporal client connection: failed reaching server: connection error: desc = \"error reading server preface: remote error: tls: certificate required\""}`

**Context:**
- Connecting to temproal cloud rather than local temporal
- Using `apiKey` rather than `mTLS` for authentication.

Pasting ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xxx
  namespace: default
spec:
  cooldownPeriod: 300
  maxReplicaCount: 3
  minReplicaCount: 0
  pollingInterval: 15
  scaleTargetRef:
    name: xxx
  triggers:
    - authenticationRef:
        kind: ClusterTriggerAuthentication
        name: keda-trigger-auth-temporal
      metadata:
        activationTargetQueueSize: '0'
        endpoint: xxx.yyy.tmprl.cloud:7233
        namespace: xxx.yyy
        targetQueueSize: '1'
        taskQueue: example_task_queue
      type: temporal
```

```
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-trigger-auth-temporal
spec:
  secretTargetRef:
    - key: temporal_apikey
      name: keda-secret
      parameter: apiKey
```

**Expected behavior:**
To be able to create the keda scaled object without any errors.

**Possible Related Issues:**
https://github.com/kedacore/keda/pull/6781#issuecomment-3001539182

**Comment by rickbrouwer** [comment]
Hi @dttung2905, friendly ping, does your PR #6820 possibly solve this problem? or is this problem different?

**Comment by dttung2905** [comment]
> Hi @dttung2905, friendly ping, does your PR #6820 possibly solve this problem? or is this problem different?

Yes it does

**Comment by cheelim1** [comment]
@dttung2905 if it does supposedly solve the problem, may you be able to suggest what i may be doing wrong? i haven't had any luck even when running with the keda `v2.17.2`.

**Comment by rickbrouwer** [comment]
There is a difference.
PR #6781 fixes the issue where TLS settings were overwritten.
PR #6820 adds support to the Temporal scaler to allow setting a custom TLS server name, see also issue #6711. This is not released yet, I expect it in v2.18.

Not completely sure, but for now I think your workaround is to pass the parameter `unsafeSsl` with the value `true`. Please let me know if this works for you.

**Comment by cheelim1** [comment]
@rickbrouwer thanks, i've tried with setting `unsafeSsl` with the value `true` but that does not seem to help. Still facing the same error.

updated the ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xxx
  namespace: default
spec:
  cooldownPeriod: 300
  maxReplicaCount: 3
  minReplicaCount: 0
  pollingInterval: 15
  scaleTargetRef:
    name: xxx
  triggers:
    - authenticationRef:
        kind: ClusterTriggerAuthentication
        name: keda-trigger-auth-temporal
      metadata:
        activationTargetQueueSize: '0'
        endpoint: xxx.yyy.tmprl.cloud:7233
        namespace: xxx.yyy
        targetQueueSize: '1'
        taskQueue: example_task_queue
        unsafeSsl: 'true'
      type: temporal
```

**Comment by ZatelNiv** [comment]
Seems to be related or the same to what i'm facing 
https://github.com/kedacore/keda/issues/6910

**Comment by sairamv-pp** [comment]
is this to be made available in 2.18 ?

**Comment by rickbrouwer** [comment]
> is this to be made available in 2.18 ?

Yeah, #6820 is merged, so this will be in 2.18.

We normally close an issue once the fix has been merged. Since the fix has been merged, I'm closing this issue. If you have any further questions or concerns about this issue, please feel free to reply in this issue.

**Comment by cheelim1** [comment]
@rickbrouwer 
I'm still facing the similar errors even in the version **2.18.2**

**Comment by dttung2905** [comment]
Hi @cheelim1 , could you provide us with the error log this time round and what was the config you were using? Were you following the new setting `tlsServerName` ?
